config/routes.rb
Zuche::Application.routes.draw do

  captcha_route

  get 'rent/new' => 'rent#new', :as => 'rent_new'

  post 'rent/comment/create/:id' => 'rent#comment_create', :as => 'rent_comment_create'

  post 'rents' => 'rent#create', :as => 'rent_create'

  get 'rents' => 'rent#index', :as => 'rents'

  get 'rent/:id' => 'rent#show', :as => 'rent'

  get 'rent_change_captcha/:id' => 'rent#change_captcha', :as => 'rent_change_captcha'

  get 'qiupin/new' => 'qiupin#new', :as => 'qiupin_new'

  post 'qiupin/comment/create/:id' => 'qiupin#comment_create', :as => 'qiupin_comment_create'

  post 'qiupins' => 'qiupin#create', :as => 'qiupin_create'

  get 'qiupins' => 'qiupin#index', :as => 'qiupins'

  get 'qiupins/filter' => 'qiupin#filter', :as => 'qiupins_filter'

  get 'qiupin/:id' => 'qiupin#show', :as => 'qiupin'

  get 'qiupin_change_captcha/:id' => 'qiupin#change_captcha', :as => 'qiupin_change_captcha'

  get 'pinche/new' => 'pinche#new', :as => 'pinche_new'

  post 'pinche/comment/create/:id' => 'pinche#comment_create', :as => 'pinche_comment_create'

  post 'pinches' => 'pinche#create', :as => 'pinche_create'

  get 'pinches' => 'pinche#index', :as => 'pinches'

  get 'pinches/filter' => 'pinche#filter', :as =>'pinches_filter'

  get 'pinche/:id' => 'pinche#show', :as => 'pinche'

  get 'pinche_change_captcha/:id' => 'pinche#change_captcha', :as => 'pinche_change_captcha'

  get 'center/pinches' => 'center#my_pinches_list', :as => 'my_pinches_list'

  get 'center/qiupins' => 'center#my_qiupins_list', :as => 'my_qiupins_list'

  get 'center/rents' => 'center#my_rents_list', :as => 'my_rents_list'

  get 'center/change_password' => 'center#change_password', :as => 'my_password'

  get 'home' => 'home#index'

  get 'contact_me' => 'home#contact_me', :as => 'contact_me'

  get 'service' => 'home#service', :as => 'service'

  get 'agreement' => 'home#agreement', :as => 'agreement'
  root :to => 'home#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

end

app/controllers/center_controller.rb
class CenterController < ApplicationController
  before_filter :is_authorize

  def my_pinches_list
    @pinches = current_user.pinches

  end

  def my_qiupins_list
    @qiupins = current_user.qiupins

  end

  def my_rents_list
    @rents = current_user.rents
  end

  def change_password

  end
end

app/views/center/change_password.html.erb
<div class="wrap">
  <div class="main">
    <div class="center_choose">
      <strong>管理信息</strong>
      <ul>
        <li>
          <%= link_to "我发布的信息", my_pinches_list_url %>
        </li>

      </ul>

      <strong>账户管理</strong>
      <ul>
        <li>
          <%= link_to "修改密码", my_password_url %>
        </li>

      </ul>
    </div>
    <div class="center_content">
      <h3>修改密码</h3>
      <%= simple_form_for(current_user, :url => registration_path(current_user), :html => {:method => :put}) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= "您的邮箱是#{current_user.email}" %>
            <%= f.input :password, :autocomplete => "off", :required => false, label: "密码" %>
            <%= f.input :password_confirmation, :required => false, label: "重复密码" %>
            <%= f.input :current_password, :hint => "当前的密码", :required => true, label: "当前密码" %>
          </div>

          <div class="form-actions" style="margin-left: 180px;">
            <%= f.button :submit, "提交", :class => "btn" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/center/my_pinches_list.html.erb
<div class="wrap">
  <div class="main">
    <div class="center_choose">
      <strong>管理信息</strong>
      <ul>
        <li>
          <%= link_to "我发布的信息", my_pinches_list_url %>
        </li>

      </ul>

      <strong>账户管理</strong>
      <ul>
        <li>
          <%= link_to "修改密码", my_password_url %>
        </li>

      </ul>
    </div>
    <div class="center_content">
      <h3>我发布的信息</h3>

      <div id="tiezi_sub_tab" class="sub_nav clearfix">
        <ul>
          <li class="current">
            <%= link_to "车找人信息", my_pinches_list_url %>
          </li>
          <li class="">
            <%= link_to "人找车信息", my_qiupins_list_url %>
          </li>
          <li class="">
            <%= link_to "租车信息", my_rents_list_url %>
          </li>
        </ul>
      </div>
      <div class="favth_thead">
        <div class="favth_col1">标题</div>
        <div class="favth_col2">帖子状态</div>
        <div class="favth_col3">发表时间</div>
        <div class="favth_col4">最后更新时间</div>
      </div>

      <ul>
        <% @pinches.each do |pinche| %>
            <li class="favth_item">
              <div class="favth_col1">
                <%= link_to truncate(pinche.title, :length => 20), pinche_path(pinche) %>
              </div>
              <div class="favth_col2">
                <%= status(pinche.is_checked) %>
              </div>
              <div class="favth_col3">
                <%= pinche.created_at.strftime("%Y-%m-%d %H:%m") %>
              </div>
              <div class="favth_col4">
                <%= pinche.updated_at.strftime("%Y-%m-%d %H:%m") %>
              </div>
              <div style="clear: both;"></div>
            </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/center/my_qiupins_list.html.erb
<div class="wrap">
  <div class="main">
    <div class="center_choose">
      <strong>管理信息</strong>
      <ul>
        <li>
          <%= link_to "我发布的信息", my_pinches_list_url %>
        </li>

      </ul>

      <strong>账户管理</strong>
      <ul>
        <li>
          <%= link_to "修改密码", my_password_url %>
        </li>

      </ul>
    </div>
    <div class="center_content">
      <h3>我发布的信息</h3>

      <div id="tiezi_sub_tab" class="sub_nav clearfix">
        <ul>
          <li class="">
          <%= link_to "车找人信息", my_pinches_list_url %>
          </li>
          <li class="current">
            <%= link_to "人找车信息", my_qiupins_list_url %>
          </li>
          <li class="">
            <%= link_to "租车信息", my_rents_list_url %>
          </li>
        </ul>
      </div>
      <div class="favth_thead">
        <div class="favth_col1">标题</div>
        <div class="favth_col2">帖子状态</div>
        <div class="favth_col3">发表时间</div>
        <div class="favth_col4">最后更新时间</div>
      </div>

      <ul>
        <% @qiupins.each do |qiupin| %>
            <li class="favth_item">
              <div class="favth_col1">
                <%= link_to truncate(qiupin.title, :length => 20), qiupin_path(qiupin) %>
              </div>
              <div class="favth_col2">
                <%= status(qiupin.is_checked) %>
              </div>
              <div class="favth_col3">
                <%= qiupin.created_at.strftime("%Y-%m-%d %H:%m") %>
              </div>
              <div class="favth_col4">
                <%= qiupin.updated_at.strftime("%Y-%m-%d %H:%m") %>
              </div>
              <div style="clear: both;"></div>
            </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/center/my_rents_list.html.erb
<div class="wrap">
  <div class="main">
    <div class="center_choose">
      <strong>管理信息</strong>
      <ul>
        <li>
          <%= link_to "我发布的信息", my_pinches_list_url %>
        </li>

      </ul>

      <strong>账户管理</strong>
      <ul>
        <li>
          <%= link_to "修改密码", my_password_url %>
        </li>

      </ul>
    </div>
    <div class="center_content">
      <h3>我发布的信息</h3>

      <div id="tiezi_sub_tab" class="sub_nav clearfix">
        <ul>
          <li class="">
            <%= link_to "车找人信息", my_pinches_list_url %>
          </li>
          <li class="">
            <%= link_to "人找车信息", my_qiupins_list_url %>
          </li>
          <li class="current">
            <%= link_to "租车信息", my_rents_list_url %>
          </li>
        </ul>
      </div>
      <div class="favth_thead">
        <div class="favth_col1">标题</div>
        <div class="favth_col2">帖子状态</div>
        <div class="favth_col3">发表时间</div>
        <div class="favth_col4">最后更新时间</div>
      </div>

      <ul>
        <% @rents.each do |rent| %>
            <li class="favth_item">
              <div class="favth_col1">
                <%= link_to truncate(rent.title, :length => 20), rent_path(rent) %>
              </div>
              <div class="favth_col2">
                <%= status(rent.is_checked) %>
              </div>
              <div class="favth_col3">
                <%= rent.created_at.strftime("%Y-%m-%d %H:%m") %>
              </div>
              <div class="favth_col4">
                <%= rent.updated_at.strftime("%Y-%m-%d %H:%m") %>
              </div>
              <div style="clear: both;"></div>
            </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>