config/routes.rb
Zuche::Application.routes.draw do

  captcha_route

  get 'rent/new' => 'rent#new', :as => 'rent_new'

  post 'rent/comment/create/:id' => 'rent#comment_create', :as => 'rent_comment_create'

  post 'rents' => 'rent#create', :as => 'rent_create'

  get 'rents' => 'rent#index', :as => 'rents'

  get 'rent/:id' => 'rent#show', :as => 'rent'

  get 'rent_change_captcha/:id' => 'rent#change_captcha', :as => 'rent_change_captcha'

  get 'qiupin/new' => 'qiupin#new', :as => 'qiupin_new'

  post 'qiupin/comment/create/:id' => 'qiupin#comment_create', :as => 'qiupin_comment_create'

  post 'qiupins' => 'qiupin#create', :as => 'qiupin_create'

  get 'qiupins' => 'qiupin#index', :as => 'qiupins'

  get 'qiupins/filter' => 'qiupin#filter', :as => 'qiupins_filter'

  get 'qiupin/:id' => 'qiupin#show', :as => 'qiupin'

  get 'qiupin_change_captcha/:id' => 'qiupin#change_captcha', :as => 'qiupin_change_captcha'

  get 'pinche/new' => 'pinche#new', :as => 'pinche_new'

  post 'pinche/comment/create/:id' => 'pinche#comment_create', :as => 'pinche_comment_create'

  post 'pinches' => 'pinche#create', :as => 'pinche_create'

  get 'pinches' => 'pinche#index', :as => 'pinches'

  get 'pinches/filter' => 'pinche#filter', :as =>'pinches_filter'

  get 'pinche/:id' => 'pinche#show', :as => 'pinche'

  get 'pinche_change_captcha/:id' => 'pinche#change_captcha', :as => 'pinche_change_captcha'

  get 'center/pinches' => 'center#my_pinches_list', :as => 'my_pinches_list'

  get 'center/qiupins' => 'center#my_qiupins_list', :as => 'my_qiupins_list'

  get 'center/rents' => 'center#my_rents_list', :as => 'my_rents_list'

  get 'center/change_password' => 'center#change_password', :as => 'my_password'

  get 'home' => 'home#index'

  get 'contact_me' => 'home#contact_me', :as => 'contact_me'

  get 'service' => 'home#service', :as => 'service'

  get 'agreement' => 'home#agreement', :as => 'agreement'
  root :to => 'home#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  menu_nav_highlight :nav_home
  def index
    @pinches = Pinche.checked.order('set_top').order('id desc').limit(10)
    @rents = Rent.checked.order('id desc').limit(10)
    @qiupins = Qiupin.checked.order('id desc').limit(10)
    @companies = Company.order('id desc').limit(10)
  end

  def contact_me

  end

  def service

  end

  def agreement

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/agreement.html.erb
<div class="wrap">
  <h3>使用协议：</h3>

  <b>泸州拼客网服务协议 </b>

  <p>本协议由您与泸州拼客网共同缔结，本协议具有合同效力。</p>

  <p>本协议中协议双方合称协议方，本协议中“泸州拼客网”，指由泸州拼客网运营的、为拥有车辆的司机及需要拼车的乘客提供信息平台，这些服务可通过www.0830pk.com以及其他可实现泸州拼客网此种服务的网址和移动程序设备应用上获取。</p>


  <b>一、协议内容及签署</b>

  <p>1.
    本协议内容包括协议正文及所有泸州拼客网已经发布的或将来可能发布的各类规则。所有规则为本协议不可分割的组成部分，以协议正文具有同等法律效力。除另行明确声明外，任何泸州拼客网及其关联公司提供的服务（以下称为泸州拼客网服务）均受本协议约束。</p>

  <p>2.
    您应当在使用泸州拼客网服务之前认真阅读全部协议内容，对于协议中以加粗字体显示的内容，您应当重点阅读。如您对协议有任何疑问的，应向泸州拼客网咨询。但无论您事实上是否在使用泸州拼客网服务之前认真阅读了本协议内容，只要您使用泸州拼客网服务，即视为您与泸州拼客网缔结本协议，本协议即对您产生约束，届时您不应以未阅读本协议的内容或者未获得泸州拼客网对您问询的解答等理由，主张本协议无效，或要求撤销本协议。</p>

  <p>3. 您承诺接受并遵守本协议的约定。如果您不同意本协议的约定，您应立即停止注册程序或停止使用泸州拼客网服务。</p>

  <p>4.
    泸州拼客网有权根据需要不时地制订、修改本协议及各类规则，并以网站公示的方式进行公告，不再单独通知您。变更后的协议和规则一经在网站发布后，立即自动生效。如您不同意相关变更，应立即停止使用泸州拼客网服务。如您继续使用泸州拼客网服务，即表示您接受经修订的协议。</p>

  <b>二、泸州拼客网服务使用规范</b>

  <p>在泸州拼客网上使用泸州拼客网服务过程中，您承诺遵守以下约定：

  <p>

  <p>a)在使用泸州拼客网服务过程中实施的所有行为均遵守中华人民共和国法律、法规等规范性文件及泸州拼客网各项的规定和要求，不违背社会公共利益或公共道德，不损害他人合法权益，不违反本协议及相关规则。您如果违反前述承诺，产生任何法律后果的，您应以自己的名义独立承担所有的法律责任，并确保泸州拼客网免于因此产生任何损失。</p>

  <p>b）在与其他会员交易过程中，遵守诚实信用原则，不采取不正当竞争行为，不扰乱网上交易的正常秩序，不从事与网上交易无关的行为。</p>

  <p>c）不发布国家禁止销售的或限制销售的商品或服务信息，不发布涉嫌侵犯他人知识产权或其它合法权益的商品或服务信息，不发布违背社会公共利益或公共道德或被认为不适合在泸州拼客网上销售的商品或服务信息，不发布其它涉嫌违法或违反本协议及各类规则的信息。</p>

  <p>d）不以虚构或歪曲事实的方式不当评价其他会员，不采取不正当方式制造或提高自身的信用度，不采取不正当方式制造或提高（降低）其他会员的信用度。</p>

  <p>e）不对泸州拼客网上的任何数据作商业性利用，包括但不限于在未经泸州拼客网事先书面同意的情况下，以复制、传播等任何方式使用泸州拼客网网站上展示的资料。</p>

  <p>f）不使用任何装置、软件或例行程序干预或试图干预泸州拼客网的正常运作或正在泸州拼客网上进行的任何交易、活动。您不得采取任何将导致不合理的庞大数据负载加诸泸州拼客网网络设备的行动。</p>
</div>

app/views/home/contact_me.html.erb
<div class="wrap">
  <h3>广告联系:</h3>
  <p>QQ:458820296</p>
  <p>EMAIL:wangyu_fine@sina.com</p>
</div>

app/views/home/index.html.erb
<div class="wrap">
  <div class="main">
    <div class="PartTime">
      <div class="gbc_corner qiupin_corner"></div>
      <span class="more"><%= link_to "更多", qiupins_url %></span>
      <ul>
        <% @qiupins.each do |qiupin| %>
            <li>
              <span style="width: 280px;"><%= link_to truncate(qiupin.title, :length => 20), qiupin_path(qiupin) %></span>
              <span style="width: 70px;"><%= DateTime.parse(qiupin.go_time).strftime("%m-%d %H:%M") %></span>
            </li>
        <% end %>
      </ul>
    </div>

    <div class="PartTime">
      <div class="gbc_corner pinche_corner"></div>
      <span class="more"><%= link_to "更多", pinches_url %></span>
      <ul>
        <% @pinches.each do |pinche| %>
            <li>
              <span style="width: 280px;">
                <%= link_to truncate(pinche.title, :length => 20), pinche_path(pinche) %>
                <% if pinche.set_top != 999 %>
                    <%= image_tag "hot_1.gif" %>
                  <% end %>
              </span>
              <span style="width: 70px;"><%= DateTime.parse(pinche.go_time).strftime("%m-%d %H:%M") %></span>
            </li>
        <% end %>
      </ul>
    </div>

    <div class="ToPost">
      <%= link_to "", pinche_new_url, :class => "btn-1" %>
      <br>
      <%= link_to "", qiupin_new_url, :class => "btn-2" %>
      <br>
      <%= link_to "", rent_new_url, :class => "btn-3" %>
    </div>
  </div>
</div>

<table width="1001" border="0" align="center" cellpadding="0" cellspacing="0">
  <tbody>
  <tr>
    <td><a href="http://www.0830pk.com/rent/1" target="_blank"><img src="/assets/tiao.jpg" alt="广告位招商" width="1001" height="90" border="0"></a></td>
  </tr>
  <tr>
    <td><a href="http://www.0830pk.com/pinche/16" target="_blank"><img src="/assets/tiao2.gif" alt="广告位招商" width="1001" height="90" border="0"></a></td>
  </tr>
  </tbody>
</table>

<div class="wrap">
  <div class="main">
    <div class="indexqz">
      <div class="gbc_corner zuche_corner"></div>
      <span class="more" style="float:right"><%= link_to "更多", rents_url %></span>
      <ul>
        <% @rents.each do |rent| %>
            <li>
              <em><%= link_to truncate(rent.title, :length => 20), rent_path(rent) %></em>
              <span style="width: 50px;"> <%= rent.style %> </span>
              <span style="width: 50px;"> <%= rent.price %>/天 </span>
              <span style="width: 75px;"> <%= rent.departure %> </span>
            </li>
        <% end %>
      </ul>
    </div>

    <div class="Recruitment">
      <div class="gbc_corner hezuo_corner"></div>
      <span class="more"></span>
      <ul>
        <% @companies.each do |company| %>
            <li>
              <%= link_to company.title, company.link, :target => "_blank" %>
            </li>
        <% end%>
      </ul>
    </div>
  </div>
</div>

app/views/home/service.html.erb
<div class="wrap">
  <h3>服务申明：</h3>

  <p>
    本网站的拼车服务，旨于为拥有车辆的司机，及需要拼车的乘客提供拼车信息平台，以此减少车辆行驶对环境造成的影响，
    我们遵守中华人民共和国的任何法律法规，对恶意利用本站信息资源，进行非法运营车辆的信息，欢迎大家随时向本站举报。
  </p>
</div>