config/routes.rb
Zuche::Application.routes.draw do

  captcha_route

  get 'rent/new' => 'rent#new', :as => 'rent_new'

  post 'rent/comment/create/:id' => 'rent#comment_create', :as => 'rent_comment_create'

  post 'rents' => 'rent#create', :as => 'rent_create'

  get 'rents' => 'rent#index', :as => 'rents'

  get 'rent/:id' => 'rent#show', :as => 'rent'

  get 'rent_change_captcha/:id' => 'rent#change_captcha', :as => 'rent_change_captcha'

  get 'qiupin/new' => 'qiupin#new', :as => 'qiupin_new'

  post 'qiupin/comment/create/:id' => 'qiupin#comment_create', :as => 'qiupin_comment_create'

  post 'qiupins' => 'qiupin#create', :as => 'qiupin_create'

  get 'qiupins' => 'qiupin#index', :as => 'qiupins'

  get 'qiupins/filter' => 'qiupin#filter', :as => 'qiupins_filter'

  get 'qiupin/:id' => 'qiupin#show', :as => 'qiupin'

  get 'qiupin_change_captcha/:id' => 'qiupin#change_captcha', :as => 'qiupin_change_captcha'

  get 'pinche/new' => 'pinche#new', :as => 'pinche_new'

  post 'pinche/comment/create/:id' => 'pinche#comment_create', :as => 'pinche_comment_create'

  post 'pinches' => 'pinche#create', :as => 'pinche_create'

  get 'pinches' => 'pinche#index', :as => 'pinches'

  get 'pinches/filter' => 'pinche#filter', :as =>'pinches_filter'

  get 'pinche/:id' => 'pinche#show', :as => 'pinche'

  get 'pinche_change_captcha/:id' => 'pinche#change_captcha', :as => 'pinche_change_captcha'

  get 'center/pinches' => 'center#my_pinches_list', :as => 'my_pinches_list'

  get 'center/qiupins' => 'center#my_qiupins_list', :as => 'my_qiupins_list'

  get 'center/rents' => 'center#my_rents_list', :as => 'my_rents_list'

  get 'center/change_password' => 'center#change_password', :as => 'my_password'

  get 'home' => 'home#index'

  get 'contact_me' => 'home#contact_me', :as => 'contact_me'

  get 'service' => 'home#service', :as => 'service'

  get 'agreement' => 'home#agreement', :as => 'agreement'
  root :to => 'home#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

end

app/models/qiupin.rb
# coding: utf-8
class Qiupin < ActiveRecord::Base
  attr_accessible :title, :body, :user, :tel, :des_province, :des_city, :des_county, :des_desc, :dep_province,
                  :dep_city, :dep_county, :dep_desc,:go_time,
                  :contact, :user_id, :is_checked
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  scope :unchecked, where(:is_checked => false)
  scope :checked, where(:is_checked => true)
  scope :all

  validates :title, :presence => true, :length => { :minimum => 4, :message => "标题必须大于4个字符"  }
  validates :go_time, :presence => true
  validates :dep_desc, :presence => true
  validates :des_desc, :presence => true

  validates :contact, :presence => true
  validates :tel, :presence => true, :format => { :with => /\d{11}/,
                                                  :message => "请留您真实的手机号码" },
            :length => { :is => 11, :message => "请输入手机号码"  }


end

app/controllers/qiupin_controller.rb
# coding: utf-8

class QiupinController < ApplicationController
  menu_nav_highlight :nav_qiupin
  before_filter :is_authorize, :only => ['new', 'create', 'comment_create']

  def index
    @qiupins = Qiupin.checked.order('id desc').paginate(:page => params[:page], :per_page => 30)
  end

  def show
    @qiupin = Qiupin.find(params[:id])
    @comment = Comment.new
    @seo_title = "#{@qiupin.title} - 泸州拼客网"
    @seo_description = " #{@qiupin.body[0..100]}"
  end

  def new
    @qiupin = Qiupin.new()
  end

  def create
    @qiupin = Qiupin.new(params[:qiupin])
    @qiupin.user = current_user
    respond_to do |format|
      if @qiupin.save
        format.html {redirect_to qiupin_path(@qiupin)}
      else
        format.html {render :action => :new}
      end
    end
  end

  def comment_create

    require "pp"
    pp "--------------------"
    pp @comment
    @qiupin = Qiupin.find(params[:id])
    @comment = @qiupin.comments.new(params[:comment])
    @comment.user = current_user
    respond_to do |format|
      if !(captcha_valid? params[:captcha])
        format.js { render :partial => 'error_captcha' }
      elsif captcha_valid? params[:captcha] and @comment.save
        format.js
      end
    end


  end

  def change_captcha
   @qiupin = Qiupin.find(params[:id])
   @comment = Comment.new
   respond_to do |format|
     format.html
     format.js
   end
  end

  def filter
    @param = params[:qiupin]
    @qiupins = Qiupin.checked
    @qiupins = @qiupins.where(:des_province => @param[:des_province]) if !@param[:des_province].blank?
    @qiupins = @qiupins.where(:des_city => @param[:des_city]) if !@param[:des_city].blank?
    @qiupins = @qiupins.where(:des_county => @param[:des_county]) if !@param[:des_county].blank?
    @qiupins = @qiupins.order('id desc').paginate(:page => params[:page], :per_page => 30)
  end


end

app/helpers/qiupin_helper.rb
module QiupinHelper
end

app/views/qiupin/_error_captcha.js.erb
var content = "<%= escape_javascript(render "report_form" )%>"

$("#repeat_comment").html(

        content
);

app/views/qiupin/_form.html.erb
<style type="text/css">
    .ui-timepicker-div .ui-widget-header {
        margin-bottom: 8px;
    }

    .ui-timepicker-div dl {
        text-align: left;
    }

    .ui-timepicker-div dl dt {
        height: 25px;
        margin-bottom: -25px;
    }

    .ui-timepicker-div dl dd {
        margin: 0 10px 10px 65px;
    }

    .ui-timepicker-div td {
        font-size: 90%;
    }

    .ui-tpicker-grid-label {
        background: none;
        border: none;
        margin: 0;
        padding: 0;
    }

    .ui_tpicker_hour_label, .ui_tpicker_minute_label, .ui_tpicker_second_label,
    .ui_tpicker_millisec_label, .ui_tpicker_time_label {
        padding-left: 20px
    }

</style>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="/assets/jquery-ui-form.js"></script>
<script type="text/javascript" src="/assets/jquery-ui-slide.min.js"></script>
<script type="text/javascript" src="/assets/jquery-ui-timepicker-addon.js"></script>
<script type="text/javascript">
    $(function () {
        $('#go_time').datetimepicker();
    })
</script>

<%= simple_form_for @qiupin, :url => qiupin_create_url do |f| %>
    <div class="merchant-box">

      <%= f.input :title, label: '标题' %>
      <%= f.input :go_time,as: :string, input_html: {id: "go_time"}, label: '出发时间',:readonly => true %>
      <p></p>

      <%#= f.input :departure, label: '出发地' %>
      <%#= f.input :destination, label: '目的地' %>

      <div class="string required">
        <label class="string required"><abbr title="required">*</abbr> 出发地点</label>
        <select id="dep_province" name="qiupin[dep_province]" class="required" required="required"></select>&nbsp;&nbsp;
        <select id="dep_city" name="qiupin[dep_city]" class="required" required="required" ></select>&nbsp;&nbsp;
        <select id="dep_county" name="qiupin[dep_county]" class="required" required="required"></select>
      </div>
      <%= f.input :dep_desc, label: '详细地址' %>

      <div class="string required">
        <label class="string required"><abbr title="required">*</abbr> 目的地点</label>
        <select id="des_province" name="qiupin[des_province]" class="required" required="required" ></select>&nbsp;&nbsp;
        <select id="des_city" name="qiupin[des_city]" class="required" required="required" ></select>&nbsp;&nbsp;
        <select id="des_county" name="qiupin[des_county]" class="required" required="required"></select>
      </div>
      <%= f.input :des_desc, label: '详细地址' %>

      <%= f.input :contact, label: '联系人' %>
      <%= f.input :tel, label: '联系电话' %>
      <%= f.input :body, input_html: {style: 'height:300px; width:412px;'}, label: '详情' %>


    </div>

    <div class="btn-box clearfix" style="margin-left: 180px;">

      <%= f.button :submit, "提交", :class => "btn" %>
    </div>
<% end %>

<script type="text/javascript" src="/assets/area.js"></script>
<script type="text/javascript">
    _init_to_area();
    _init_area();

</script>

app/views/qiupin/_new_report_form.html.erb
<%= simple_form_for Comment.new, :url => qiupin_comment_create_path(@qiupin), :remote => true do |f| %>
    <%= f.input :body, input_html: {style: 'height:100px; width:412px;'}, label: false %>
    <p>验证码: <%= captcha_tag %><span><%= link_to "换一张", qiupin_change_captcha_path(@qiupin), :remote => true %></span></p>
    <p><%= text_field_tag :captcha %></p>
    <%= f.button :submit, "提交", :class => "btn" %>



<% end %>

app/views/qiupin/_repeat.html.erb
<li style="display: none;">
  <p class="commentdetail_txt">
    <%= @comment.body %>
  </p>

  <div class="commentdetail_bar">
    <p> <%= @comment.created_at.strftime("%Y-%m-%d %H:%m") %>
      来自:<%= (@comment.user) ? (@comment.user.name) : "匿名" %> </p>

  </div>
</li>

app/views/qiupin/_report_form.html.erb
  <%= simple_form_for @comment, :url => qiupin_comment_create_path(@qiupin), :remote => true do |f| %>
      <%= f.input :body, input_html: {style: 'height:100px; width:412px;'}, label: false %>
      <p>验证码: <%= captcha_tag %> <span><%= link_to "换一张", qiupin_change_captcha_path(@qiupin), :remote => true %></span>
      </p>

      <p><%= text_field_tag :captcha %></p>
      <%= f.button :submit, "提交", :class => "btn" %>


  <% end %>

app/views/qiupin/change_captcha.js.erb
var content = "<%= escape_javascript(render "report_form" )%>"

$("#repeat_comment").html(

    content
);

app/views/qiupin/comment_create.js.erb
var content = "<%= escape_javascript(render "new_report_form" )%>"

$("#repeat_comment").html(

        content
);

$("#comment_body").text("");

$(".comment_list ul").append("<%= escape_javascript(render :partial => 'repeat') %>");

$('.comment_list ul li:last').show("slow");

app/views/qiupin/filter.html.erb
<div class="topclass">
  <div style="float:left;width: 700px; ">
    <p>筛选条件</p>

    <form action="/qiupins/filter" method="get">
      <b>目的地</b>
      省份：<select id="des_province" name="qiupin[des_province]" class="filter"></select>&nbsp;&nbsp;
      市：<select id="des_city" name="qiupin[des_city]" class="filter"></select>&nbsp;&nbsp;
      区县：<select id="des_county" name="qiupin[des_county]" class="filter"></select>

      <input name="search_submit" type="submit" value="确定"/>
    </form>
  </div>
  <div style="float:right;width: 169px; height: 60px;">
    <%= link_to "", qiupin_new_url, :class => "btn-2" %>
  </div>

</div>

<div class="topclass">
  <div>您选择的筛选条件为：  目的地【<%= condition(@param)%>】 </div>
  <div class="listcontent">

    <div class="joblist">
      <ul>
        <li>
          <span style="width:400px;">车找人信息</span>
          <span style="width:200px;">出发地</span>
          <span style="width:200px;">目的地</span>
          <span style="width: 150px;">发车时间</span>
        </li>
        <% @qiupins.each do |qiupin| %>
            <li>
              <span style="width: 275px;">
                  <%= link_to truncate(qiupin.title, :length => 30), qiupin_path(qiupin), :class => "Linklist" %>
              </span>
              <span style="width: 200px;"><%= "#{qiupin.dep_city},#{qiupin.dep_county}" %></span>
              <span style="width: 200px;"><%= "#{qiupin.des_city},#{qiupin.des_county}" %></span>
              <span style="width: 150px;"><%= qiupin.go_time %></span>
            </li>
        <% end %>


      </ul>
      <%= will_paginate @qiupins %>
    </div>
  </div>
</div>

<script type="text/javascript" src="/assets/area.js"></script>
<script type="text/javascript">
    _init_to_area();

</script>

app/views/qiupin/index.html.erb
<div class="topclass">
  <div style="float:left;width: 700px; ">
    <p>筛选条件</p>

    <form action="/qiupins/filter" method="get">
      <b>目的地</b>
      省份：<select id="des_province" name="qiupin[des_province]" class="filter"></select>&nbsp;&nbsp;
      市：<select id="des_city" name="qiupin[des_city]" class="filter"></select>&nbsp;&nbsp;
      区县：<select id="des_county" name="qiupin[des_county]" class="filter"></select>
      <input name="search_submit" type="submit" value="确定"/>
    </form>
  </div>
  <div style="float:right;width: 169px; height: 60px;">
    <%= link_to "", qiupin_new_url, :class => "btn-2" %>
  </div>

</div>

<div class="topclass">
  <div class="listcontent">
    <div class="joblist">
      <ul>
        <li>
          <span style="width:400px;">人找车信息</span>
          <span style="width:200px;">出发地</span>
          <span style="width:200px;">目的地</span>
          <span style="width: 150px;">发车时间</span>
        </li>
        <% @qiupins.each do |qiupin| %>
            <li>
              <span style="width:400px;">
                 <%= link_to truncate(qiupin.title, :length => 30), qiupin_path(qiupin), :class => "Linklist" %>
              </span>
              <span style="width: 200px;"><%= "#{qiupin.dep_city},#{qiupin.dep_county}" %></span>
              <span style="width: 200px;"><%= "#{qiupin.des_city},#{qiupin.des_county}" %></span>
              <span style="width: 150px;"><%= qiupin.go_time %></span>
            </li>
        <% end %>


      </ul>
      <%= will_paginate @qiupins %>
    </div>
  </div>
</div>

<script type="text/javascript" src="/assets/area.js"></script>
<script type="text/javascript">
    _init_to_area();

</script>

app/views/qiupin/new.html.erb
<div class="wrap">
  <div class="title">
    <h3 class="f18 col63">发布求拼信息</h3>
  </div>
  <div id="claim_form">
    <div class="merchant-wrap">
      <div class="s-title">
        <h4>信息详情</h4>
      </div>
      <%= render 'form' %>


    </div>
  </div>
</div>

app/views/qiupin/show.html.erb
<div class="jobct">
  <div class="d_cname">
    <%= link_to "泸州租车网", root_url %>  »<%= link_to "人找车", qiupins_url %> » <%= @qiupin.title %>
  </div>

  <div class="d_left">
    <h2><%= @qiupin.title %></h2>
    <span>发布时间： <%= @qiupin.created_at.strftime("%Y-%m-%d %H:%m") %> </span>
    <br>
    <span>出发时间: <%= @qiupin.go_time %> </span>
    <br>
    <span>所在地：<%= "#{@qiupin.dep_province} - #{@qiupin.dep_city} - #{@qiupin.dep_county} - #{@qiupin.dep_desc}" %></span>
    <br>
    <span>目的地：<%= "#{@qiupin.des_province} - #{@qiupin.des_city} - #{@qiupin.des_county} - #{@qiupin.des_desc}" %></span>
    <br>



    <div class="ad300" style="border: 1px solid darkred">这个可以是广告</div>

    <div class="d_content">

      <%= @qiupin.body %>
      <br><br>
      联系我时请说明在泸州拼车网上看到的
      <br>
      联系人：<%= @qiupin.contact %>

      <br>
      电话：<%= @qiupin.tel %>

      <div class="suggest">提示：本站信息全部来源于互联网，请广大网友谨防受骗上当</div>
    </div>

  </div>

  <div style="clear:both;"></div>

  <div class="comment_block">
    <font> 回复 </font>
  </div>

  <div class="comment_list">
    <ul>
      <% @qiupin.comments.each do |comment| %>
          <li>
            <p class="commentdetail_txt">
              <%= comment.body %>
            </p>

            <div class="commentdetail_bar">
              <p> <%= comment.created_at.strftime("%Y-%m-%d %H:%m") %>
                来自:<%= (comment.user) ? (comment.user.name) : "匿名" %> </p>

            </div>
          </li>
      <% end %>
    </ul>

  </div>

  <%# if !current_user.blank? %>
      <div id="repeat_comment">
        <%= render "report_form" %>
      </div>
  <%# end %>

</div>